apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: enterprise-argocd-project
  namespace: argocd
spec:
  description: Enterprise argoCD deployment environment

  sourceRepos:
    - '*'

  destinations:
    - namespace: enterprise-argocd
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
